### ISSUE TITLE
Error message when trying to import

### ISSUE THREAD

**Issue by znre** [jensb89/Netflix-to-Trakt-Import#22]
Traceback (most recent call last):
  File "C:\Users\[user]\Desktop\Netflix-to-Trakt-Import-master\netflix2trakt.py", line 69, in <module>
    tmp = tmdbSeason.details(tv_id=showId, season_num=i, append_to_response="translations")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python311\Lib\site-packages\tmdbv3api\objs\season.py", line 29, in details
    return AsObj(
           ^^^^^^
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python311\Lib\site-packages\tmdbv3api\as_obj.py", line 9, in __init__
    raise TMDbException(entries["status_message"])
tmdbv3api.exceptions.TMDbException: The resource you requested could not be found.

**Comment by jensb89** [comment]
Did you fill in a valid TMDB API Id? 
Can you check if the log file gives more information? 
Is it happening directly at the beginning or after some movies/shows were already processed?

**Comment by znre** [comment]
Yep I filled in a valid TMDB API ID. The log file doesn’t give more
information, basically the same as the command prompt output. It happens
after some shows were already processed.

**Comment by jensb89** [comment]
That's good, do you know at which entry it fails? Then I can try to reproduce it.
(Or provide a part of your csv file?) 

Also the debug mode might help for more output in the log

**Comment by znre** [comment]
Hmm not sure at which entry it fails tho. I could just provide the csv file. I'll post it in another comment so I can delete it later haha.

**Comment by znre** [comment]
Here it is
[NetflixViewingHistory.csv](https://github.com/jensb89/Netflix-to-Trakt-Import/files/10328548/NetflixViewingHistory.csv)

**Comment by jensb89** [comment]
Thanks, I will have a look to see what might goes wrong.

**Comment by jensb89** [comment]
Ok, seems the script is searching for all seasons of "untold". The show info from TMDB says there are 14 seasons, but when requesting season 10, TMDB doesn't have one (the correct one only has 1 season and 2 episodes by the way). That is more a bug in the TMDB API (wrapper). Anyway,I will add a check for that and skip the show in that case as the show cannot be matched correctly.

**Comment by jensb89** [comment]
Should work now, the entry is skipped for now, as it is not so easy to match (the same format is used for "TvShow: Season Name: Episode x" as well. In your case it was "Tv Show: Tv Show Subtile: Part x" that produced the error.

But the rest should run through :)

**Comment by znre** [comment]
Thank you very much! :)
