### ISSUE TITLE
Error trying to connect to OAuth Trakt it seems.

### ISSUE THREAD

**Issue by EugeneKallis** [jensb89/Netflix-to-Trakt-Import#45]
`DEBUG:urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
DEBUG:urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
DEBUG:trakt.core.emitter:[trakt.client.TraktClient          ]:on(events: ['oauth.token_refreshed'], func: <bound method TraktIO.on_token_refreshed of <TraktIO.TraktIO object at 0x101ee0ac0>>)
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): api.trakt.tv:80
DEBUG:urllib3.connectionpool:http://api.trakt.tv:80 "POST /oauth/device/code HTTP/1.1" 301 167
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.trakt.tv:443
DEBUG:urllib3.connectionpool:https://api.trakt.tv:443 "GET /oauth/device/code HTTP/1.1" 404 None
WARNING:trakt.interfaces.base:Request failed: "GET /oauth/device/code" - 404: "Method exists, but no record found" (Not Found)
`
I created API key on Trakt like it was listed but I keep getting this error. I noticed on Trakt there's an Authorize button next to the OAuth URL and it gives me a pin. am I suppose to do something with that?

**Comment by ebzao** [comment]
Hi,

I had same bug, and I've fixed it with adding s to http://api.trakt.tv/ line 29 in TraktIO.py to become https://api.trakt.tv/.

Then :

> python3 netflix2trakt.py
Enter the code "AABBCC1122" at https://trakt.tv/activate to authenticate your account

and it was OK!

**Comment by EugeneKallis** [comment]
that fixed it! thank you!

**Comment by jensb89** [comment]
Thanks for the help guys!
