### ISSUE TITLE
time data '12.04.2022 20:15' does not match format

### ISSUE THREAD

**Issue by DavidWillQuitThis** [jensb89/Netflix-to-Trakt-Import#8]
Hi, trying to import my data and being told the date format is incorrect.  The data in my spreadsheet looks like this:

Title,Date
"Seinfeld: Season 9: The Bookstore","12/04/2022"
"Jimmy Savile: A British Horror Story: Limited Series: Part 2","12/04/2022"
"Jimmy Savile: A British Horror Story: Limited Series: Part 1","11/04/2022"

It's d, m, y.  The error says:

ValueError: time data '12.04.2022 20:15' does not match format '%d.%m.%y %H:%M'

From what I can tell it should? Is there something I can edit in the config to fix it?  Thanks!

e: I changed the y in the date format to Y and that fixed it.

**Comment by RileyXX** [comment]
I also had a similar problem. For me it was because my time netflix history csv file format was in '%m.%d.%y %H:%M'. Just had to edit the config.py file and swapped it from %d.%m.%y to %m.%d.%y
