### ISSUE TITLE
Not syncing to trakt?

### ISSUE THREAD

**Issue by xFaultx** [jensb89/Netflix-to-Trakt-Import#9]
Running on windows, I think I have everything setup right, but Trakt itself is not updating. I was never prompted to give a pin for the app, so possibly thats part of the problem. When I run the python script, I get this at the end (after listing a bunch of movies/shows as found and not found)

```
Traceback (most recent call last):
  File "C:\XXXX\Netflix-To-Trakt\netflix2trakt.py", line 87, in <module>
    tmdbResult = tmdbSeason.details(tv_id=showId, season_num=season.number, append_to_response="translations")
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\site-packages\tmdbv3api\objs\season.py", line 29, in details
    return AsObj(
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\site-packages\tmdbv3api\as_obj.py", line 9, in __init__
    raise TMDbException(entries["status_message"])
tmdbv3api.exceptions.TMDbException: The resource you requested could not be found.
```

**Comment by jensb89** [comment]
Sry for the late reply, busy week...

The error actually looks like there is something wrong with the TMDB search for the movie/tv show. So the script doesn't even reach the part, where all data is sent to Trakt. Thus, you are also not prompted to give a pin yet.

A few things to check out for: 
-  Have you put the API key for a TmDB account in the config?
- Try with a reduced csv file first. Maybe just try a csv file with just 10 entries or less. It might fail just for a specific tv show right now, maybe with some unknown character in it.
- If both is not helping: Have a look in the Netflix2TraktImportLog.log file. Is there more information given? Does the error occur for the first tv show/movie of the csv file, or a later one?
- Are you using the specified versions of all packages via the requirements.txt file?
